# Generated by Django 3.0.8 on 2020-08-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreation',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
