# Generated by Django 3.0.8 on 2020-08-02 15:51

import applicants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=40)),
                ('address_line2', models.CharField(blank=True, max_length=40)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=255)),
                ('highest_level_of_education', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('key_skills', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to=applicants.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('job_applied_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.Applicant')),
            ],
        ),
    ]
