# Generated by Django 3.0.8 on 2020-08-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='job_applied_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.JobCreation'),
        ),
    ]
